project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sls.qmd
        text: Schedule
    right:
      - text: Archive
        menu:
          - text: Cohort 10 (2023-4)
            href: Cohort 10\cohort10.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

